/**
 * Retrieval-grounded scientific assistant.
 *
 * The retrieved records are shown alongside every answer, not hidden behind a
 * disclosure. That is the point of the feature: the answer is a reading of
 * those records, and the reader can check it.
 */

import { api } from "../api.js";
import { card, empty, esc, evidenceBadge, kindBadge, loading, notice } from "../ui.js";
import { wireNav } from "./entity.js";

const EXAMPLES = [
  "How does levodopa work in Parkinson disease?",
  "What drugs target acetylcholinesterase?",
  "Which targets are associated with Alzheimer disease?",
  "What experimentally determined structures exist for monoamine oxidase B?",
  "Compare the mechanisms of fingolimod and ocrelizumab.",
  "Which pathways involve alpha-synuclein?",
];

export async function aiView(root) {
  const status = await api.aiStatus();

  root.innerHTML = `
    <div class="page-head">
      <h2>AI scientist</h2>
      <p class="lede">
        Ask a question and get an answer assembled from the platform's own
        source records. Retrieval runs first; the model may only use what was
        retrieved, and every citation is checked against those records before
        it is shown.
      </p>
    </div>

    ${
      status.generation_enabled
        ? notice(
            `Narrative answers are generated by <strong>${esc(
              status.model
            )}</strong> over retrieved records. ${esc(status.note)}`,
            "info",
            "🤖"
          )
        : notice(
            `<strong>No language model is configured.</strong> Questions still
             work: the assistant retrieves and displays the matching source
             records, which is the evidence an answer would have been built
             from. Set <code>ANTHROPIC_API_KEY</code> to enable narrative
             answers.`,
            "muted",
            "◌"
          )
    }

    ${notice(
      `This assistant does not provide medical advice, diagnosis, or treatment
       recommendations. If it cannot support an answer from retrieved records,
       it is instructed to say so rather than fill the gap.`,
      "warn",
      "⚕"
    )}

    <div class="card">
      <div class="row" style="align-items:stretch">
        <input type="text" id="question" placeholder="Ask a scientific question…"
               style="flex:1;font-size:14px;padding:10px 13px" />
        <button class="primary" id="ask">Ask</button>
      </div>
      <div class="mt">
        <span class="small dim">Try:</span>
        ${EXAMPLES.map(
          (q) => `<span class="chip clickable" data-q="${esc(q)}">${esc(q)}</span>`
        ).join("")}
      </div>
    </div>

    <div id="chat" class="chat"></div>`;

  const input = root.querySelector("#question");
  const chat = root.querySelector("#chat");

  const ask = async (question) => {
    if (!question.trim()) return;
    input.value = "";

    chat.insertAdjacentHTML(
      "beforeend",
      `<div class="msg msg-user">${esc(question)}</div>
       <div class="msg msg-ai" id="pending">${loading("Retrieving records…")}</div>`
    );
    chat.lastElementChild.scrollIntoView({ behavior: "smooth", block: "nearest" });

    try {
      const result = await api.aiAsk(question);
      document.querySelector("#pending").outerHTML = answerMarkup(result);
    } catch (error) {
      document.querySelector("#pending").outerHTML = `
        <div class="msg msg-ai">
          ${notice(`Request failed: ${esc(error.message)}`, "danger", "⚠")}
        </div>`;
    }
    wireNav(chat);
    chat.querySelectorAll("[data-toggle-records]").forEach((node) =>
      node.addEventListener("click", () => {
        const target = document.getElementById(node.dataset.toggleRecords);
        target?.classList.toggle("hidden");
      })
    );
  };

  root.querySelector("#ask").addEventListener("click", () => ask(input.value));
  input.addEventListener("keydown", (event) => {
    if (event.key === "Enter") ask(input.value);
  });
  root.querySelectorAll("[data-q]").forEach((chip) =>
    chip.addEventListener("click", () => ask(chip.dataset.q))
  );
}

function answerMarkup(result) {
  const id = `rec-${Math.random().toString(36).slice(2, 9)}`;

  const entities = (result.entities || [])
    .slice(0, 14)
    .map(
      (e) =>
        `<span class="chip clickable" data-nav="#/entity/${e.id}">
           ${kindBadge(e.kind)} ${esc(e.name)}
         </span>`
    )
    .join("");

  const body = result.answer
    ? `<div>${linkCitations(result.answer)}</div>`
    : `<div class="notice notice-muted" style="margin:0 0 12px">
         <span class="ico">◌</span>
         <div>${esc(result.note || "No narrative answer was generated.")}</div>
       </div>`;

  const warning = result.citation_warning
    ? `<div class="notice notice-danger" style="margin:12px 0 0">
         <span class="ico">⚠</span><div>${esc(result.citation_warning)}
         Removed: ${(result.rejected_citations || [])
           .map((c) => `<span class="cite cite-removed">${esc(c)}</span>`)
           .join(" ")}
         </div>
       </div>`
    : "";

  return `
    <div class="msg msg-ai">
      ${body}
      ${warning}
      ${
        entities
          ? `<div class="mt"><div class="small dim mb">Entities retrieved</div>${entities}</div>`
          : ""
      }
      <div class="row mt">
        <button class="sm" data-toggle-records="${id}">
          Show the ${result.record_count} source records used
        </button>
        <span class="small dim">${esc(result.disclaimer)}</span>
      </div>
      <div id="${id}" class="hidden mt">
        ${recordsMarkup(result.records || [])}
      </div>
    </div>`;
}

function recordsMarkup(records) {
  if (!records.length) return empty("No records retrieved.");
  return `<div class="table-scroll" style="max-height:420px">
    ${records
      .map(
        (r) => `
        <div style="padding:9px 0;border-bottom:1px solid var(--border)">
          <div class="row">
            <span class="chip">${esc(r.kind)}</span>
            ${
              r.evidence_level
                ? `<span class="small dim">${esc(r.evidence_level)}</span>`
                : ""
            }
          </div>
          <div class="small" style="margin-top:4px">
            ${Object.entries(r)
              .filter(
                ([k, v]) =>
                  k !== "kind" &&
                  k !== "evidence_level" &&
                  v !== null &&
                  v !== undefined &&
                  v !== ""
              )
              .slice(0, 8)
              .map(
                ([k, v]) =>
                  `<div><span class="dim">${esc(k)}:</span> ${esc(
                    typeof v === "object" ? JSON.stringify(v) : String(v).slice(0, 300)
                  )}</div>`
              )
              .join("")}
          </div>
        </div>`
      )
      .join("")}
  </div>`;
}

/** Turn validated inline citations into external links. */
function linkCitations(text) {
  const escaped = esc(text);
  return escaped
    .replace(
      /\[PMID:\s*(\d+)\]/g,
      '<a class="cite" href="https://pubmed.ncbi.nlm.nih.gov/$1/" target="_blank" rel="noopener">PMID:$1</a>'
    )
    .replace(
      /\[NCT:\s*(NCT\d+)\]/g,
      '<a class="cite" href="https://clinicaltrials.gov/study/$1" target="_blank" rel="noopener">$1</a>'
    )
    .replace(
      /\[PDB:\s*([0-9][A-Za-z0-9]{3})\]/g,
      '<a class="cite" href="https://www.rcsb.org/structure/$1" target="_blank" rel="noopener">PDB:$1</a>'
    )
    .replace(
      /\[(?:ChEMBL|CHEMBL):\s*(CHEMBL\d+)\]/gi,
      '<a class="cite" href="https://www.ebi.ac.uk/chembl/compound_report_card/$1/" target="_blank" rel="noopener">$1</a>'
    )
    .replace(
      /\[(?:UniProt|UNIPROT):\s*([A-Z0-9]+)\]/gi,
      '<a class="cite" href="https://www.uniprot.org/uniprotkb/$1" target="_blank" rel="noopener">UniProt:$1</a>'
    )
    .replace(/\n\n/g, "</p><p>")
    .replace(/^/, "<p>")
    .replace(/$/, "</p>");
}

/* ------------------------------------------------------- 3D explorer hub */

export async function explorerView(root) {
  root.innerHTML = loading();
  const [structures, compounds] = await Promise.all([
    api.structures({ limit: 60 }),
    api.entities({ kind: "compound", limit: 60 }),
  ]);

  root.innerHTML = `
    <div class="page-head">
      <h2>3D explorer</h2>
      <p class="lede">
        Experimentally determined macromolecular structures and small-molecule
        conformers. Each viewer states what kind of structure it is showing.
      </p>
    </div>

    ${notice(
      `Experimental structures and computed models are labelled differently
       everywhere they appear. This platform does not generate docking poses,
       and no predicted binding mode is ever displayed alongside solved
       coordinates as though it were observed.`,
      "warn",
      "⬢"
    )}

    <div class="grid grid-2">
      ${card(
        `Experimental structures <span class="dim">(${structures.total})</span>`,
        structures.items.length
          ? `<div class="table-scroll" style="max-height:520px">
               ${structures.items
                 .map(
                   (s) => `
                   <div class="entity-row" data-nav="#/entity/${s.id}">
                     <span class="kind-badge kind-structure">${esc(s.pdb_id || "PDB")}</span>
                     <div class="body">
                       <div class="name">${esc(
                         (s.description || s.name || "").slice(0, 90)
                       )}</div>
                       <div class="meta">${esc(s.method || "")}${
                     s.resolution ? ` · ${s.resolution.toFixed(2)} Å` : ""
                   }${
                     (s.ligands || []).length
                       ? ` · ${s.ligands.length} bound ligand(s)`
                       : ""
                   }</div>
                     </div>
                   </div>`
                 )
                 .join("")}
             </div>`
          : empty("No structures ingested.")
      )}
      ${card(
        `Small-molecule conformers <span class="dim">(${compounds.total})</span>`,
        compounds.items.length
          ? `<div class="table-scroll" style="max-height:520px">
               ${compounds.items
                 .map(
                   (c) => `
                   <div class="entity-row" data-nav="#/entity/${c.id}">
                     ${kindBadge("compound")}
                     <div class="body">
                       <div class="name">${esc(c.name)}</div>
                       <div class="meta mono">${esc(c.detail?.formula || "")}</div>
                     </div>
                     <div class="right small dim">${
                       c.detail?.has_3d ? "3D available" : "no 3D"
                     }</div>
                   </div>`
                 )
                 .join("")}
             </div>`
          : empty("No compounds ingested.")
      )}
    </div>`;
  wireNav(root);
}
