/**
 * 3D Molecular Lab.
 *
 * Real geometry from RDKit's ETKDG embedding with force-field minimisation,
 * rendered by the vendored 3Dmol.js the atlas already ships. The 2D depiction
 * beside it is server-rendered from the same parsed structure, so the two views
 * cannot disagree.
 *
 * Conformers are labelled as computed geometry throughout, using the atlas's
 * own structure-provenance banner — a generated conformer is not an observed
 * one, and the amber banner is what keeps that visible.
 */

import { card, esc, notice, structureBanner } from "../../ui.js";
import { MoleculeViewer, viewerToolbar } from "../../viewer-molecule.js";
import { bindJob } from "../../jobstore.js";
import { labApi } from "../api.js";
import { needsStructure, needsSubject } from "../router.js";
import { subjectStore } from "../store.js";
import { provBadge, wireProvenance } from "../ui.js";

let viewer = null;

export async function mol3dView(root, params) {
  const subject = subjectStore.get();
  const smiles = params?.get("smiles") || subject?.smiles;

  if (!subject && !smiles) {
    root.innerHTML = needsSubject("the 3D Molecular Lab");
    return;
  }

  root.innerHTML = `
    <div class="toolbar mb">
      <input class="search-input" id="m-smiles" type="text" spellcheck="false"
             placeholder="SMILES" value="${esc(smiles || "")}"
             style="flex:1;min-width:280px" />
      <label class="row small">Conformers
        <select id="m-count"><option>3</option><option selected>5</option><option>10</option></select>
      </label>
      <span id="m-run"></span>
    </div>
    <div id="m-body"></div>`;

  if (!smiles) {
    root.querySelector("#m-body").innerHTML = needsStructure(subject);
    return;
  }

  // Keyed by structure: typing a different SMILES is a different run, and must
  // not reattach to the previous molecule's ensemble.
  const bind = () =>
    bindJob(root, `lab-conformers:${root.querySelector("#m-smiles").value.trim()}`, {
      control: "#m-run",
      output: "#m-body",
      runLabel: "Generate",
      autoStart: true,
      start: () => startConformers(root),
      render: (host, ensemble) => showEnsemble(host, ensemble),
    });

  let unbind = bind();
  root.querySelector("#m-smiles").addEventListener("change", () => {
    unbind();
    unbind = bind();
  });
}

function startConformers(root) {
  const smiles = root.querySelector("#m-smiles").value.trim();
  if (!smiles) throw new Error("Supply a structure.");
  return labApi.conformers({
    smiles,
    count: Number(root.querySelector("#m-count").value),
  });
}

async function showEnsemble(body, ensemble) {
  try {
    await paintEnsemble(body, ensemble);
  } catch (error) {
    body.innerHTML = notice(esc(error.message), "danger", "⚠");
  }
}

async function paintEnsemble(body, ensemble) {
  if (!ensemble?.available) {
    body.innerHTML = notice(
      `<strong>No 3D structure could be generated.</strong> ${esc(
        ensemble?.reason || ""
      )}`,
      "warn",
      "⚠"
    );
    return;
  }

  // Both panels are built from the structure the run actually used, not from
  // whatever is in the input box now.
  const smiles = ensemble.structure.canonical_smiles;
  const profile = await labApi.analyse(smiles);

  body.innerHTML = `
    <div class="grid grid-2">
      ${card(
        "3D conformer",
        `${structureBanner({
          kind: "computed_conformer",
          label: "Computed 3D conformer",
          warning:
            "Generated by distance geometry and minimised in vacuum. Not an " +
            "experimentally observed geometry and not a receptor-bound pose.",
        })}
        ${viewerToolbar([
          { action: "style", value: "stick", label: "Sticks" },
          { action: "style", value: "ball", label: "Ball & stick" },
          { action: "style", value: "sphere", label: "Space-filling" },
          { action: "style", value: "surface", label: "Surface" },
          { action: "labels", label: "Atom labels" },
          { action: "measure", label: "Measure" },
          { action: "reset", label: "Reset" },
        ])}
        <div class="viewer" id="m-viewer"><div class="viewer-loading">Loading…</div></div>
        <div class="row" style="margin-top:8px">
          <label class="small">Conformer
            <select id="m-conf">
              ${ensemble.conformers
                .map(
                  (conformer) =>
                    `<option value="${conformer.rank - 1}">#${conformer.rank} · ${
                      conformer.energy ?? "—"
                    } kcal/mol${
                      conformer.relative_energy
                        ? ` (+${conformer.relative_energy})`
                        : " (lowest)"
                    }</option>`
                )
                .join("")}
            </select>
          </label>
          <span class="spacer"></span>
          <span class="small dim" id="m-measure"></span>
        </div>
        <div class="lab-note" id="m-conf-note"></div>`
      )}

      ${card(
        "2D structure",
        `<div class="mol-2d">
          <img src="${esc(labApi.depictionUrl(smiles, 420, 320))}" alt="2D structure" />
        </div>
        <dl class="kv mt">
          <dt>Formula</dt><dd>${esc(profile.structure.formula)}</dd>
          <dt>InChIKey</dt><dd class="mono small">${esc(
            profile.structure.inchikey || "—"
          )}</dd>
          <dt>Canonical SMILES</dt><dd class="mono small">${esc(
            profile.structure.canonical_smiles
          )}</dd>
        </dl>
        <div class="lab-note">
          The depiction is rendered on the server from the same parsed structure
          the conformers were built from, so the two views cannot disagree.
        </div>`
      )}
    </div>

    ${card(
      "Conformer ensemble",
      `<table class="wb-table">
        <tr><th>Rank</th><th>Energy</th><th>Relative</th><th>RMSD to lowest</th></tr>
        ${ensemble.conformers
          .map(
            (conformer) => `<tr>
              <td>#${conformer.rank}</td>
              <td class="num">${conformer.energy ?? "—"}</td>
              <td class="num">${conformer.relative_energy ?? "—"}</td>
              <td class="num">${conformer.rmsd_to_lowest ?? "—"}</td>
            </tr>`
          )
          .join("")}
      </table>
      <div class="row mt">
        <span class="small dim">Force field: ${esc(ensemble.force_field)} ·
          energies in ${esc(ensemble.energy_units)} ·
          seed ${ensemble.seed} · pruned at ${ensemble.prune_rms_threshold} Å RMSD</span>
        ${provBadge(ensemble.provenance)}
      </div>
      <ul class="small muted mt" style="padding-left:17px">
        ${ensemble.caveats.map((caveat) => `<li>${esc(caveat)}</li>`).join("")}
      </ul>`
    )}

    ${card(
      "Calculated properties",
      propertyTable(profile)
    )}`;

  wireProvenance(body);
  mountViewer(body, ensemble);
}

function propertyTable(profile) {
  const descriptors = profile.descriptors || {};
  const rows = Object.entries(descriptors)
    .map(
      ([key, record]) => `<tr>
        <td>${esc(record.label || key)}</td>
        <td class="num">${record.value ?? "—"}</td>
        <td class="dim">${esc(record.units || "")}</td>
        <td>${provBadge(record.provenance)}</td>
      </tr>`
    )
    .join("");

  const alerts = profile.alerts;
  return `<table class="wb-table">
      <tr><th>Descriptor</th><th>Value</th><th>Units</th><th>Provenance</th></tr>
      ${rows}
    </table>
    <div class="mt">
      <strong>Structural alerts:</strong> ${alerts.count}
      ${provBadge(alerts.provenance)}
      ${
        alerts.value.length
          ? `<ul class="small muted" style="padding-left:17px">${alerts.value
              .slice(0, 6)
              .map(
                (hit) =>
                  `<li>${esc(hit.name)} <span class="dim">(${esc(
                    hit.catalog || ""
                  )})</span></li>`
              )
              .join("")}</ul>`
          : `<span class="dim small"> — none matched</span>`
      }
      <div class="lab-note">${esc(alerts.provenance.note)}</div>
    </div>
    <div class="mt">
      <strong>Scaffold:</strong>
      <span class="mono small">${esc(profile.scaffold.scaffold_smiles || "—")}</span>
    </div>`;
}

function mountViewer(root, ensemble) {
  const host = root.querySelector("#m-viewer");
  const select = root.querySelector("#m-conf");
  const note = root.querySelector("#m-conf-note");
  const measure = root.querySelector("#m-measure");

  viewer?.viewer?.clear?.();
  viewer = new MoleculeViewer(host, { computed: true });
  if (!viewer.init()) return;

  const load = (index) => {
    const conformer = ensemble.conformers[index];
    host.querySelector(".viewer-loading")?.remove();
    viewer.viewer.clear();
    viewer.model = viewer.viewer.addModel(conformer.molblock, "sdf");
    viewer.applyStyle();
    viewer.viewer.zoomTo();
    viewer.viewer.render();
    viewer.attachPicking();
    note.textContent =
      `Showing conformer #${conformer.rank}: ${conformer.energy ?? "—"} ` +
      `${ensemble.energy_units}` +
      (conformer.relative_energy
        ? `, ${conformer.relative_energy} above the lowest.`
        : ", the lowest-energy member of this ensemble.");
  };

  viewer.onMeasure = (distance) => {
    measure.textContent = `Distance: ${distance.toFixed(2)} Å`;
  };

  select.addEventListener("change", () => load(Number(select.value)));
  load(0);

  root.querySelectorAll(".viewer-toolbar button").forEach((button) => {
    button.addEventListener("click", () => {
      const { action, value } = button.dataset;
      if (action === "style") viewer.setStyleMode(value);
      else if (action === "labels") viewer.toggleLabels();
      else if (action === "measure") {
        const on = viewer.toggleMeasure();
        button.classList.toggle("primary", on);
        measure.textContent = on ? "Click two atoms to measure." : "";
      } else if (action === "reset") viewer.reset();
    });
  });
}
